apiVersion: v1
kind: Namespace
metadata:
  name: asdasdasd-dev
  labels:
    environment-id: env_9d2e0e86-616f-46d0-9d95-9eeb66e757de
    project-id: project_9dc93dcf-ba66-4f5c-bcaf-99b959dda842
    project-name: asdasdasd
    environment-name: dev
    organization-id: org_1c58789b-c98c-4917-b321-116968ec4f8e
